version: '3.8'

services:
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '${REDIS_STORE}:/bitnami'
    ports:
      - 6379
    expose:
      - 6379

  backend:
    depends_on:
      - redis
    image: sebastianweb/capstone-project-backend
    container_name: sebmedia_backend
    restart: unless-stopped
    volumes:
      - '${UPLOAD_DIR}:/uploads'
    ports:
      - 8080:8080
    expose:
      - 8080
    #environment:
      #- MONGODB_URI=MongoDB
      - REDIS_URL=redis://redis:6379


  frontend:
    depends_on:
      - backend
      - redis
    image: sebastianweb/capstone-project-frontend
    container_name: sebmedia_frontend
    restart: unless-stopped
    ports:
      - 80:80
    expose:
      - 80
