version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
    volumes:
      - '/home/ec2-user/redis-store:/bitnami'

  backend:
    depends_on:
      - redis
    image: sebastianweb/capstone-project-backend
    container_name: sebmedia_backend
    restart: unless-stopped
    ports:
      - 8080
    expose:
      - 8080


  frontend:
    depends_on:
      - backend
      - redis
    image: sebastianweb/capstone-project-frontend
    container_name: sebmedia_frontend
    restart: unless-stopped
    ports:
      - 80
    expose:
      - 80