version: '3.8'

services:
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/home/ec2-user/redis-store:/bitnami'
    ports:
      - 6379
    expose:
      - 6379

  backend:
    depends_on:
      - redis
    image: sebastianweb/capstone-project-backend
    container_name: sebmedia_backend
    restart: unless-stopped
    ports:
      - 8080:8080
    expose:
      - 8080


  frontend:
    depends_on:
      - backend
      - redis
    image: sebastianweb/capstone-project-frontend
    container_name: sebmedia_frontend
    restart: unless-stopped
    ports:
      - 80:80
    expose:
      - 80
