name: Test-Cases

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x]
        os: ['ubuntu-latest', 'windows-latest', 'macOS-latest']
    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install for tests folder
      run: cd tests && npm install

    - name: npm install for backend folder
      run: cd backend && npm install

    - name: Run tests
      run: cd tests && node tests
